### ISSUE TITLE
Build error in French xml strings resource

### ISSUE THREAD

**Issue by alvinhochun** [topjohnwu/Magisk#2169]
Suspect to be regression from b4d0ad971314b4370b5eeb46d52feb8dbfe06903:

```
   > Android resource compilation failed
     /home/alvin/magisk/src/app/src/main/res/values-fr/strings.xml:149:5-84: AAPT: error: unescaped apostrophe in string
         
     /home/alvin/magisk/src/app/src/main/res/values-fr/strings.xml:149:5-84: AAPT: error: not a valid string.
         
     /home/alvin/magisk/src/app/src/main/res/values-fr/strings.xml:151:5-95: AAPT: error: unescaped apostrophe in string
         
     /home/alvin/magisk/src/app/src/main/res/values-fr/strings.xml:151:5-95: AAPT: error: not a valid string.
         
     /home/alvin/magisk/src/app/src/main/res/values-fr/strings.xml:171:5-141: AAPT: error: unescaped apostrophe in string
         
     /home/alvin/magisk/src/app/src/main/res/values-fr/strings.xml:171:5-141: AAPT: error: not a valid string.
         
     /home/alvin/magisk/src/app/src/main/res/values-fr/strings.xml:170:5-95: AAPT: error: unescaped apostrophe in string
         
     /home/alvin/magisk/src/app/src/main/res/values-fr/strings.xml:170:5-95: AAPT: error: not a valid string.
         
     /home/alvin/magisk/src/app/src/main/res/values-fr/strings.xml:32:5-200: AAPT: error: unescaped apostrophe in string
         
     /home/alvin/magisk/src/app/src/main/res/values-fr/strings.xml:32:5-200: AAPT: error: not a valid string.
         
     /home/alvin/magisk/src/app/src/main/res/values-fr/strings.xml:11:5-258: AAPT: error: unescaped apostrophe in string
         
     /home/alvin/magisk/src/app/src/main/res/values-fr/strings.xml:11:5-258: AAPT: error: not a valid string.
         
     /home/alvin/magisk/src/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-fr/values-fr.xml: AAPT: error: file failed to compile.
```
